import localFont from "next/font/local";
import "./globals.css";
import Meta from "@/components/Meta.js"
import SkipNav from "@/layout/SkipNav.jsx";
import Header from "@/layout/Header/Header";

export const metadata = {
  title: "Clio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
    <head>
      <Meta />
      <title>{metadata.title}</title>
    </head>
    <body>
      <SkipNav />
      <div className="wrap">
        <Header />
        {children}
      </div>
    </body>
    </html>
  );
}
